/* Rooftop English — 問題データ
 * 毎週金曜のニュースレター要約（knowledge/weeks/）から AI が更新する。
 * ルール：
 *  - 問題の id は一度付けたら変えない（進捗が id に紐づく）。直すときは中身だけ直す。
 *  - 本（Rooftoppers 等）の本文は使わない。例文はすべて自作。
 *  - 名前・学校名など個人が特定できる情報は入れない。
 *  - unit.status: "next"=来週の予習 / "review"=やった単元の復習 / "bank"=いつでも
 */
window.RE_CONTENT = {
  version: "2026-09-13",

  units: [
    {
      id: "m05-blog",
      status: "next",
      when: "Week of 14 Sep",
      title: "Polishing a travel blog",
      ja: "旅行ブログの推敲（来週の授業の予習）",
      source: "Michaelmas W4 ニュースレター（9/11）：来週はパリ旅行ブログを書き上げて推敲＝語彙の格上げ・描写・文の構成・句読点",
      speak: [
        "Describe a favourite place in Singapore in two sentences, as if for a travel blog. Use one sense word (a smell, a sound or a taste) and talk to “you”, the reader.",
        "Say one sentence about a food you love that starts with a fronted adverbial — for example, “On hot afternoons, …”",
        "Imagine the last line of your Paris blog. Say it in a way that makes the reader want to pack their bags."
      ]
    },
    {
      id: "m02-characters",
      status: "review",
      when: "Weeks 2–3",
      title: "Reading characters",
      ja: "人物を読む（Rooftoppers の人物描写の復習）",
      source: "Michaelmas W1–W2：重要語彙の洗い出し → 行動・言葉・関係から人物像を読む → ロールプレイ・インタビュー",
      speak: [
        "Think of a character from a book you love. Say one trait word for them, and one thing they DO that shows it.",
        "Pretend to interview a character. Ask them one “how” or “why” question out loud, then answer as them."
      ]
    },
    {
      id: "m03-notes",
      status: "review",
      when: "Week 3",
      title: "Research notes & paraphrasing",
      ja: "調べ学習のメモと言い換え（復習）",
      source: "Michaelmas W3：パリを調べて要約しながらメモ → 自分の言葉で言い換え → 構成を立ててノンフィクションを書く",
      speak: [
        "Read one short paragraph in any book. Close the book and say what it was about in ONE sentence, in your own words."
      ]
    },
    {
      id: "spelling",
      status: "bank",
      when: "Anytime",
      title: "Tricky spellings",
      ja: "Year 5・6 必修スペリング（イギリス式つづり）",
      source: "UK National Curriculum の Year 5/6 statutory word list から",
      speak: [
        "Pick one word you got wrong today. Spell it out loud with your eyes closed, then use it in a sentence."
      ]
    },
    {
      id: "grammar",
      status: "bank",
      when: "Anytime",
      title: "Grammar toolkit",
      ja: "文法の道具箱（Year 6 の文法用語）",
      source: "UK National Curriculum Year 6 の文法（受動態・仮定法・品詞・フォーマルな言い方 など）",
      speak: [
        "Say one sentence about your weekend in the active voice. Now say the same thing in the passive voice."
      ]
    }
  ],

  skills: {
    "word-choice": { en: "Choosing words", ja: "文脈に合う言葉選び" },
    "sentence-craft": { en: "Building sentences", ja: "文の組み立て" },
    "punctuation": { en: "Punctuation", ja: "句読点" },
    "blog-features": { en: "Blog features", ja: "ブログらしい書き方" },
    "character-vocab": { en: "Character words", ja: "人物を表す語彙" },
    "inference": { en: "Reading between the lines", ja: "行間を読む（推論）" },
    "paraphrase": { en: "Paraphrasing & notes", ja: "言い換え・メモ・要約" },
    "spelling": { en: "Spelling", ja: "スペリング" },
    "grammar": { en: "Grammar terms", ja: "文法用語" }
  },

  items: [
    /* ───────── m05-blog : word-choice ───────── */
    { id: "bl-wc-01", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Choose the best word: The view from the top of the Eiffel Tower was ___ — the whole city spread out below us like a map.",
      options: ["breathtaking", "big", "nice", "huge"], a: 0,
      why: "“Breathtaking” tells the reader how the view made you FEEL. “Big” and “huge” only describe size, and “nice” tells us almost nothing.",
      hint: "breathtaking＝息をのむほどの" },
    { id: "bl-wc-02", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Choose the best word: The street market is ___ on Saturday mornings: stalls, shoppers and the smell of fresh bread everywhere.",
      options: ["stunning", "bustling", "ancient", "silent"], a: 1,
      why: "“Bustling” means full of busy people and movement — exactly what the rest of the sentence describes. “Stunning” is about beauty, not busyness.",
      hint: "人がたくさんいて、にぎやかな様子を表す言葉は？" },
    { id: "bl-wc-03", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Which description would make a blog reader hungriest? “The croissants were ___.”",
      options: ["good", "very very nice", "buttery and flaky", "food"], a: 2,
      why: "Specific sense words (taste, texture) let the reader imagine eating it. General words like “good” don’t paint a picture.",
      hint: "味や食感が伝わるのはどれ？ flaky＝サクサクと層になった" },
    { id: "bl-wc-04", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Choose the best word: We ___ along the River Seine, stopping every few minutes to look at the old bookstalls.",
      options: ["sprinted", "strolled", "went", "marched"], a: 1,
      why: "“Strolled” means walked slowly and happily — it fits a relaxed stop-and-look walk. “Sprinted” and “marched” are too fast or too stiff, and “went” doesn’t say HOW.",
      hint: "stroll＝のんびり歩く" },
    { id: "bl-wc-05", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Choose the best word: Notre-Dame is a ___ cathedral that is more than 800 years old.",
      options: ["cosy", "cute", "magnificent", "fine"], a: 2,
      why: "“Cosy” and “cute” suit small, friendly things. “Magnificent” fits something grand and impressive.",
      hint: "壮大で立派なものに合う言葉は？" },
    { id: "bl-wc-06", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Careful — the fanciest word isn’t always best! Which sentence gives the most useful travel advice?",
      options: [
        "The metro is a magnificent, breathtaking way to get around Paris.",
        "The metro is a quick and cheap way to get around Paris.",
        "The metro is a nice way to get around Paris.",
        "The metro is a colossal way to get around Paris."
      ], a: 1,
      why: "For practical advice, clear precise words (quick, cheap) do the job better than grand describing words. Match the word to the job.",
      hint: "実用的な情報を伝えるなら、具体的でわかりやすい言葉が一番" },
    { id: "bl-wc-07", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Which word best shows how enormous the museum is? “The Louvre is so ___ that you could spend a week inside and still not see every room.”",
      options: ["tall", "vast", "heavy", "narrow"], a: 1,
      why: "“Vast” means extremely large in AREA — lots of space to walk around. “Tall” is about height, “heavy” about weight, and “narrow” means the opposite.",
      hint: "vast＝広大な" },
    { id: "bl-wc-08", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "The streets are paved with small, rounded stones. Which word describes them? “The narrow, ___ streets wind up the hill.”",
      options: ["cobbled", "fluffy", "bustling", "modern"], a: 0,
      why: "“Cobbled” describes the street surface (small rounded stones) — a detail the reader can see and almost feel underfoot.",
      hint: "cobbled＝石畳の" },
    { id: "bl-wc-09", unit: "m05-blog", skill: "word-choice", type: "mc",
      q: "Choose the best word: “Look at all those lights!” my brother ___ excitedly.",
      options: ["muttered", "whispered", "exclaimed", "mumbled"], a: 2,
      why: "The exclamation mark and “excitedly” tell us he spoke loudly with excitement. “Muttered”, “whispered” and “mumbled” are all quiet.",
      hint: "「！」と excitedly に合う “said” の言い換えは？" },

    /* ───────── m05-blog : sentence-craft ───────── */
    { id: "bl-sc-01", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "Which sentence uses a relative clause correctly?",
      options: [
        "The Arc de Triomphe, who stands at the top of the Champs-Élysées, is huge.",
        "The Arc de Triomphe, which stands at the top of the Champs-Élysées, is huge.",
        "The Arc de Triomphe which, stands at the top of the Champs-Élysées is huge.",
        "The Arc de Triomphe, stands at the top of the Champs-Élysées, is huge."
      ], a: 1,
      why: "Use “which” for things and “who” for people. The commas go around the WHOLE extra piece of information.",
      hint: "もの→which、人→who。カンマは追加情報のかたまり全体をはさむ" },
    { id: "bl-sc-02", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "Join these: “We climbed to the top of the hill. We watched the sunset.” Which is correct?",
      options: [
        "We climbed to the top of the hill we watched the sunset.",
        "We climbed to the top of the hill, we watched the sunset.",
        "After we climbed to the top of the hill, we watched the sunset.",
        "After we climbed to the top of the hill. We watched the sunset."
      ], a: 2,
      why: "A conjunction (after) joins the two ideas, and a comma follows the opening clause. The first two run the sentences together; the last one leaves “After we climbed…” unfinished on its own.",
      hint: "カンマだけで2つの文をつなぐのは間違い（comma splice）" },
    { id: "bl-sc-03", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "Which sentence starts with a fronted adverbial?",
      options: [
        "The tower sparkled with lights as the sun set.",
        "As the sun set, the tower sparkled with lights.",
        "Sparkling lights covered the tower.",
        "The tower sparkled."
      ], a: 1,
      why: "A fronted adverbial is moved to the FRONT of the sentence and tells us when, where or how. It is followed by a comma.",
      hint: "「いつ・どこで・どのように」が文頭に来て、後ろにカンマ" },
    { id: "bl-sc-04", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "Every sentence in a paragraph starts with “Then”. Which opener adds the most variety?",
      options: ["And then,", "Then,", "Moments later,", "So then,"], a: 2,
      why: "“Moments later,” moves the story on in time without repeating “then”. Varied openers keep readers interested.",
      hint: "Then を使わずに時間の流れを表すのはどれ？" },
    { id: "bl-sc-05", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "Which is the strongest expanded noun phrase?",
      options: [
        "a nice café",
        "a very very small café",
        "a café",
        "a tiny café with red chairs spilling onto the pavement"
      ], a: 3,
      why: "It adds a precise adjective (tiny) AND a detail after the noun (with red chairs…). “Very very” just repeats without adding a picture.",
      hint: "名詞の前後に情報を足して、絵が浮かぶようにしたもの" },
    { id: "bl-sc-06", unit: "m05-blog", skill: "sentence-craft", type: "mc",
      q: "After three long sentences, a writer adds: “Then we saw it.” Why use such a short sentence?",
      options: [
        "To build surprise or suspense",
        "Because they ran out of ideas",
        "To list several things",
        "To ask the reader a question"
      ], a: 0,
      why: "A short sentence after long ones makes the reader stop. It’s a way to create drama or surprise.",
      hint: "長い文のあとの短い文＝効果をねらっている" },

    /* ───────── m05-blog : punctuation ───────── */
    { id: "bl-pu-01", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Which sentence is punctuated correctly?",
      options: [
        "In Paris we ate, croissants, crêpes, macarons and cheese.",
        "In Paris we ate croissants, crêpes, macarons and cheese.",
        "In Paris we ate croissants crêpes, macarons, and, cheese.",
        "In Paris we ate croissants; crêpes; macarons and cheese."
      ], a: 1,
      why: "Commas separate the items in a list. There is no comma before the first item, and simple lists don’t need semicolons.",
      hint: "リストのカンマは「項目と項目の間」だけ" },
    { id: "bl-pu-02", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Which is correct?",
      options: [
        "The citys oldest bridge is the Pont Neuf.",
        "The citys’ oldest bridge is the Pont Neuf.",
        "The city’s oldest bridge is the Pont Neuf.",
        "The cities oldest bridge is the Pont Neuf."
      ], a: 2,
      why: "One city owns the bridge, so it’s city + ’s = city’s.",
      hint: "「その街の」＝持ち主は1つの city" },
    { id: "bl-pu-03", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "The Eiffel Tower is repainted about every seven years to protect ___ iron.",
      options: ["it’s", "its", "its’", "it is"], a: 1,
      why: "“Its” (no apostrophe) means “belonging to it”. “It’s” always means “it is” or “it has”.",
      hint: "it is に置き換えて意味が通るなら it’s。通らないなら its" },
    { id: "bl-pu-04", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Where does the colon belong?",
      options: [
        "You will need: three things for Paris comfortable shoes, a map and an appetite.",
        "You will need three things: for Paris comfortable shoes, a map and an appetite.",
        "You will need three things for Paris; comfortable shoes, a map and an appetite.",
        "You will need three things for Paris: comfortable shoes, a map and an appetite."
      ], a: 3,
      why: "A colon introduces a list, and it comes after a complete sentence (“You will need three things for Paris”).",
      hint: "コロンの前は、それだけで文として成り立つ" },
    { id: "bl-pu-05", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Which uses a semicolon correctly?",
      options: [
        "The museum was crowded; the gardens outside were peaceful.",
        "The museum was; crowded and noisy.",
        "We visited; the museum and the gardens.",
        "The museum was crowded; and noisy."
      ], a: 0,
      why: "A semicolon joins two complete sentences that are closely linked. Both sides must make sense on their own.",
      hint: "セミコロンの両側は、どちらも完全な文" },
    { id: "bl-pu-06", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Which uses brackets correctly?",
      options: [
        "The Seine (the river that flows through Paris) is lined with bookstalls.",
        "The Seine (the river that flows) through Paris is lined with bookstalls.",
        "The Seine the river (that flows through Paris is lined) with bookstalls.",
        "(The Seine the river) that flows through Paris is lined with bookstalls."
      ], a: 0,
      why: "Brackets hold EXTRA information. Test it: cover the brackets — “The Seine is lined with bookstalls” still makes sense.",
      hint: "かっこの中を消しても文が成り立つか確かめる" },
    { id: "bl-pu-07", unit: "m05-blog", skill: "punctuation", type: "mc",
      q: "Which is punctuated correctly?",
      options: [
        "“Can we go up the tower”? asked Leo.",
        "“Can we go up the tower,” asked Leo?",
        "“Can we go up the tower?” asked Leo.",
        "Can we go up the tower? “asked Leo.”"
      ], a: 2,
      why: "The question mark belongs to the spoken words, so it goes INSIDE the inverted commas. The sentence ends with a full stop after “Leo”.",
      hint: "? は話した言葉の一部＝引用符の内側" },

    /* ───────── m05-blog : blog-features ───────── */
    { id: "bl-bf-01", unit: "m05-blog", skill: "blog-features", type: "mc",
      q: "Travel blogs often talk straight to the reader. Which sentence does that?",
      options: [
        "The lifts are small.",
        "You won’t believe how tiny the lifts are!",
        "The writer visited the tower.",
        "Lifts were invented a long time ago."
      ], a: 1,
      why: "Using “you” and a lively tone makes readers feel they are there with you.",
      hint: "読者に “you” と話しかけている文は？" },
    { id: "bl-bf-02", unit: "m05-blog", skill: "blog-features", type: "mc",
      q: "Which is the best subheading for a section about food?",
      options: [
        "Paragraph 3",
        "I went to some places and ate things",
        "Where to Eat: Crêpes, Cafés and Croissants",
        "Stuff"
      ], a: 2,
      why: "A good subheading is short, tells readers exactly what’s coming, and makes them want to read on.",
      hint: "短く、中身がわかって、読みたくなる見出し" },
    { id: "bl-bf-03", unit: "m05-blog", skill: "blog-features", type: "mc",
      q: "Which is an OPINION, not a fact?",
      options: [
        "The Eiffel Tower is in Paris.",
        "The Louvre is a museum.",
        "The best view in Paris is from the top of the hill.",
        "The Seine flows through Paris."
      ], a: 2,
      why: "“The best” is a judgement — people could disagree. Facts can be checked.",
      hint: "人によって答えが変わるのが opinion" },
    { id: "bl-bf-04", unit: "m05-blog", skill: "blog-features", type: "mc",
      q: "Which is the most effective last sentence for a travel blog?",
      options: [
        "The end.",
        "So pack your bags — Paris is waiting for you!",
        "That is all I have to say.",
        "Paris is a city."
      ], a: 1,
      why: "A strong ending speaks to the reader and leaves them with a feeling (here: excitement to go).",
      hint: "読者に「行きたい！」と思わせる締めくくり" },

    /* ───────── m02-characters : character-vocab (cards) ───────── */
    { id: "ch-cv-01", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "determined", def: "Having decided to do something and not letting anything stop you.",
      ja: "決意が固い・やり抜く", ex: "Although her legs were shaking, she was determined to reach the top of the ladder." },
    { id: "ch-cv-02", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "resilient", def: "Able to recover quickly after something difficult or upsetting.",
      ja: "へこたれない・立ち直りが早い", ex: "After losing the race, the resilient runner was training again the very next morning." },
    { id: "ch-cv-03", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "eccentric", def: "Unusual in a way that is interesting and a little strange.",
      ja: "風変わりな", ex: "Her eccentric uncle wore odd socks and kept a tortoise in his study." },
    { id: "ch-cv-04", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "wary", def: "Careful because you think something might be dangerous.",
      ja: "用心深い・警戒している", ex: "The cat was wary of the new dog and watched it from the top of the wardrobe." },
    { id: "ch-cv-05", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "mischievous", def: "Enjoying playful tricks that cause small trouble.",
      ja: "いたずら好きな", ex: "The mischievous twins hid all the whiteboard pens before the lesson." },
    { id: "ch-cv-06", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "compassionate", def: "Showing that you care about people who are hurt or unhappy.",
      ja: "思いやりのある", ex: "The compassionate nurse sat with the frightened boy until his parents arrived." },
    { id: "ch-cv-07", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "defiant", def: "Openly refusing to obey or do what you are told.",
      ja: "反抗的な・負けん気の強い", ex: "With a defiant look, he folded his arms and refused to leave." },
    { id: "ch-cv-08", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "nimble", def: "Quick and light in the way you move.",
      ja: "身軽な・すばしこい", ex: "The nimble climber leapt from chimney to chimney without a sound." },
    { id: "ch-cv-09", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "precarious", def: "Not safe or steady; likely to fall or go wrong.",
      ja: "不安定な・危なっかしい", ex: "The tower of books on the chair looked precarious." },
    { id: "ch-cv-10", unit: "m02-characters", skill: "character-vocab", type: "card",
      word: "stubborn", def: "Refusing to change your mind, even when others want you to.",
      ja: "頑固な", ex: "The stubborn goat would not move off the bridge." },

    /* ───────── m02-characters : character-vocab (mc) ───────── */
    { id: "ch-cv-11", unit: "m02-characters", skill: "character-vocab", type: "mc",
      q: "A character who keeps going even after lots of problems is ___.",
      options: ["eccentric", "resilient", "wary", "mischievous"], a: 1,
      why: "“Resilient” means bouncing back after difficulties.",
      hint: "へこたれない人" },
    { id: "ch-cv-12", unit: "m02-characters", skill: "character-vocab", type: "mc",
      q: "Which word describes someone who is careful because they sense danger?",
      options: ["curious", "stubborn", "wary", "loyal"], a: 2,
      why: "“Wary” means cautious because something might be dangerous.",
      hint: "危険を感じて用心している" },
    { id: "ch-cv-13", unit: "m02-characters", skill: "character-vocab", type: "mc",
      q: "“I don’t care what the rules say — I’m going anyway!” Which trait does this show?",
      options: ["compassionate", "defiant", "wary", "nimble"], a: 1,
      why: "Refusing to follow the rules, openly, is being defiant.",
      hint: "ルールに逆らうと宣言している" },

    /* ───────── m02-characters : inference ───────── */
    { id: "ch-in-01", unit: "m02-characters", skill: "inference", type: "mc",
      q: "“Ella checked the lock three times before she went to bed.” What does this suggest about Ella?",
      options: [
        "She is lazy.",
        "She is worried about being safe.",
        "She is mischievous.",
        "She is collecting keys."
      ], a: 1,
      why: "Writers show feelings through actions. Checking three times suggests worry — the writer never says “worried”, but we can work it out.",
      hint: "3回も確かめる人の気持ちは？" },
    { id: "ch-in-02", unit: "m02-characters", skill: "inference", type: "mc",
      q: "Which sentence SHOWS (rather than tells) that Sam is nervous?",
      options: [
        "Sam was nervous.",
        "Sam felt very nervous indeed.",
        "Sam’s hands trembled as he tapped his foot again and again.",
        "Nervous is how Sam felt."
      ], a: 2,
      why: "Showing means describing what the character does or how their body reacts, so the reader works out the feeling.",
      hint: "“nervous” という言葉を使わずに伝えている文" },
    { id: "ch-in-03", unit: "m02-characters", skill: "inference", type: "mc",
      q: "Someone says: “The girl is brave.” Which is the best evidence for this?",
      options: [
        "She has brown hair.",
        "Even though her voice shook, she told the teacher what had really happened.",
        "She likes music.",
        "She lives in a big city."
      ], a: 1,
      why: "Evidence must PROVE the point. Doing the right thing even when you feel scared shows bravery.",
      hint: "「勇敢」を証明できる行動はどれ？" },
    { id: "ch-in-04", unit: "m02-characters", skill: "inference", type: "mc",
      q: "In a role-play interview, which question would tell you the MOST about a character’s feelings?",
      options: [
        "How old are you?",
        "What colour is your coat?",
        "How did you feel when you first found the note?",
        "Do you like bread?"
      ], a: 2,
      why: "Open “how” and “why” questions get deeper answers than yes/no or fact questions.",
      hint: "はい／いいえで終わらない質問" },
    { id: "ch-in-05", unit: "m02-characters", skill: "inference", type: "mc",
      q: "“He gave his last coin to the boy selling matches, then walked home hungry.” Which word fits him best?",
      options: ["compassionate", "stubborn", "eccentric", "defiant"], a: 0,
      why: "He puts someone else’s need before his own — that shows he cares about others.",
      hint: "自分が空腹でも人にあげる人" },

    /* ───────── m03-notes : paraphrase ───────── */
    { id: "nt-pa-01", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "Original: “The Eiffel Tower was built for the 1889 World’s Fair and was meant to stand for only 20 years.” Which is the best paraphrase?",
      options: [
        "The Eiffel Tower was built for the 1889 World’s Fair and was meant to stand for only 20 years.",
        "Built for a fair in 1889, the tower was only supposed to last two decades.",
        "The Eiffel Tower is very tall and made of iron.",
        "The tower was built in 1989 for 20 different fairs."
      ], a: 1,
      why: "A paraphrase keeps the SAME meaning in your OWN words. Copying isn’t paraphrasing, and the facts must stay correct.",
      hint: "意味は同じ・言葉は自分のもの・事実は正確" },
    { id: "nt-pa-02", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "Source: “The Louvre, which was once a royal palace, is now one of the most visited art museums in the world.” Which is the best NOTE?",
      options: [
        "The Louvre, which was once a royal palace, is now one of the most visited art museums in the world.",
        "Louvre nice",
        "Louvre – once royal palace – now one of world’s most-visited art museums",
        "palace"
      ], a: 2,
      why: "Good notes keep only the key facts, in short form. Copying the whole sentence isn’t note-taking; too few words lose the meaning.",
      hint: "要点だけを短く。全部写すのも、短すぎるのもダメ" },
    { id: "nt-pa-03", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "“Paris has hundreds of parks and gardens. In one, children sail toy boats on a pond. Another sits right next to a famous museum. Many are free to enter.” Best one-sentence summary?",
      options: [
        "Children sail toy boats.",
        "Paris has hundreds of parks, many free, each with something special.",
        "One garden is next to a museum.",
        "Parks are green."
      ], a: 1,
      why: "A summary covers the MAIN idea of the whole paragraph, not one detail.",
      hint: "段落全体の一番言いたいことは？" },
    { id: "nt-pa-04", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "You need the height of the Eiffel Tower for your blog. Which source is MOST reliable?",
      options: [
        "A comment under a video",
        "A friend’s guess",
        "The tower’s official website",
        "A hotel advert"
      ], a: 2,
      why: "Official sources are most likely to be accurate. Comments, guesses and adverts may be wrong or trying to sell you something.",
      hint: "一番信頼できる情報源は？" },
    { id: "nt-pa-05", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "“The Seine is about 777 kilometres long and flows through Paris into the English Channel.” Which are the KEY words to note?",
      options: [
        "the, is, about, and",
        "Seine – 777 km – through Paris – into English Channel",
        "flows, into",
        "long, the, kilometres"
      ], a: 1,
      why: "Key words are the names, numbers and facts that carry the meaning. Little words like “the” and “and” can be left out.",
      hint: "名前・数字・事実がキーワード" },
    { id: "nt-pa-06", unit: "m03-notes", skill: "paraphrase", type: "mc",
      q: "Why should you write your final blog in your own words, not copy from websites?",
      options: [
        "So it’s longer",
        "To show you understand it — and copying someone else’s writing isn’t fair",
        "So nobody can read it",
        "Because spelling doesn’t matter"
      ], a: 1,
      why: "Using your own words proves you understand the facts, and copying another writer’s words is not allowed (plagiarism).",
      hint: "丸写しは plagiarism（盗用）" },

    /* ───────── spelling (Y5/6 statutory list, British spelling) ───────── */
    { id: "sp-01", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["accomodate", "accommodate", "acommodate", "acomodate"], a: 1,
      why: "Double c AND double m: a-cc-o-mm-odate.", hint: "c も m も2つ" },
    { id: "sp-02", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["neccessary", "necesary", "necessary", "neccesary"], a: 2,
      why: "One collar, two sleeves: one c, two s’s — ne-c-e-ss-ary.", hint: "c は1つ、s は2つ" },
    { id: "sp-03", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["embarass", "embarras", "embaras", "embarrass"], a: 3,
      why: "Double r AND double s: emba-rr-a-ss.", hint: "r も s も2つ" },
    { id: "sp-04", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["definate", "definite", "defenite", "deffinite"], a: 1,
      why: "There’s a “finite” hiding inside: de-FINITE.", hint: "中に finite が隠れている" },
    { id: "sp-05", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct in British English?",
      options: ["neighbor", "nieghbour", "neighbour", "neighbur"], a: 2,
      why: "British English keeps the “ou”: neighbour. (“Neighbor” is the American spelling.)", hint: "イギリス式は -our" },
    { id: "sp-06", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["mischievious", "mischevious", "mischievous", "mischevous"], a: 2,
      why: "Say it “MIS-chiv-us” — three syllables. There is no extra “i” before -ous.", hint: "-ious ではなく -ous" },
    { id: "sp-07", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["rythm", "rhythm", "rhythem", "rhythym"], a: 1,
      why: "Rhythm Helps Your Two Hips Move: r-h-y-t-h-m.", hint: "Rhythm Helps Your Two Hips Move" },
    { id: "sp-08", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["queu", "qeue", "queue", "quewe"], a: 2,
      why: "q-u-e-u-e: the “ue” appears twice.", hint: "ue が2回" },
    { id: "sp-09", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["resturant", "restaurant", "restarant", "restaraunt"], a: 1,
      why: "rest-AU-rant: there’s a hidden “au” you don’t really hear.", hint: "聞こえにくい au がある" },
    { id: "sp-10", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["enviroment", "environmant", "environment", "envirnment"], a: 2,
      why: "There’s an “n” before -ment: enviro-N-ment.", hint: "-ment の前に n" },
    { id: "sp-11", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["temprature", "temperture", "temperature", "tempreture"], a: 2,
      why: "Say every part: tem-per-a-ture.", hint: "tem・per・a・ture と区切って" },
    { id: "sp-12", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct in British English?",
      options: ["marvelous", "marvellous", "marvelus", "marvellus"], a: 1,
      why: "British English doubles the l: marve-LL-ous. (“Marvelous” is American.)", hint: "イギリス式は l が2つ" },
    { id: "sp-13", unit: "spelling", skill: "spelling", type: "mc",
      q: "I couldn’t sleep because my ___ told me I should have said sorry.",
      options: ["conscious", "conscience", "concience", "consious"], a: 1,
      why: "Your conscience is the voice inside that tells you right from wrong. “Conscious” means awake and aware.", hint: "良心＝conscience／意識がある＝conscious" },
    { id: "sp-14", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["foriegn", "forein", "foreign", "foreighn"], a: 2,
      why: "“foreign” breaks the “i before e” rule: f-o-r-e-i-g-n.", hint: "e が先、i があと" },
    { id: "sp-15", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["twelth", "twelvth", "twelfth", "twelveth"], a: 2,
      why: "twelve → twel-F-th. The v changes to f.", hint: "v が f に変わる" },
    { id: "sp-16", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["sufficent", "suficient", "sufficient", "sufficiant"], a: 2,
      why: "Double f, and it ends -cient: su-ff-i-cient.", hint: "f が2つ、終わりは -cient" },
    { id: "sp-17", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["garantee", "guarentee", "guarantee", "guarrantee"], a: 2,
      why: "A silent “u” after g: g-U-arantee.", hint: "g のあとに発音しない u" },
    { id: "sp-18", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["occured", "ocurred", "occurred", "ocured"], a: 2,
      why: "Double c, and double r when you add -ed: o-cc-u-rr-ed.", hint: "c も r も2つ" },
    { id: "sp-19", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["vehical", "vehicle", "vehicel", "veicle"], a: 1,
      why: "A silent h, and it ends -cle: ve-H-i-cle.", hint: "発音しない h、終わりは -cle" },
    { id: "sp-20", unit: "spelling", skill: "spelling", type: "mc",
      q: "We saw a flash of ___ over the river.",
      options: ["lightening", "lightning", "litening", "lightnning"], a: 1,
      why: "Lightning is the flash in a storm. “Lightening” means making something lighter.", hint: "稲妻＝lightning（e は入らない）" },
    { id: "sp-21", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["stomache", "stomack", "stomach", "stumach"], a: 2,
      why: "It ends -ach, like “ache” without the e: stom-ACH.", hint: "終わりは -ach" },
    { id: "sp-22", unit: "spelling", skill: "spelling", type: "mc", q: "Which spelling is correct?",
      options: ["yatch", "yaht", "yacht", "yhacht"], a: 2,
      why: "y-a-c-h-t: the “ch” is silent.", hint: "ch は発音しない" },

    /* ───────── grammar toolkit ───────── */
    { id: "gr-01", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which sentence is in the passive voice?",
      options: [
        "Leonardo da Vinci painted the Mona Lisa.",
        "The Mona Lisa was painted by Leonardo da Vinci.",
        "Leonardo da Vinci was a painter.",
        "The Mona Lisa hangs in the Louvre."
      ], a: 1,
      why: "In the passive, the thing the action is done TO comes first: “The Mona Lisa was painted by…”.",
      hint: "受動態＝「〜された」。be動詞＋過去分詞（＋by）" },
    { id: "gr-02", unit: "grammar", skill: "grammar", type: "mc",
      q: "Rewrite in the active voice: “The cake was eaten by the dog.”",
      options: ["The cake ate the dog.", "The dog ate the cake.", "The dog was eating by the cake.", "The cake was eaten."], a: 1,
      why: "In the active voice the DOER (the dog) comes first and does the action.",
      hint: "する側（犬）を主語に" },
    { id: "gr-03", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which sentence uses the subjunctive?",
      options: [
        "If I am tall, I can see.",
        "If I were taller, I could see over the crowd.",
        "I was tall last year.",
        "When I grow, I will see."
      ], a: 1,
      why: "The subjunctive uses “were” for imagined situations, even after “I”: “If I were…”. It sounds formal.",
      hint: "仮定法＝If I were ...（I でも were）" },
    { id: "gr-04", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which sign is the most formal?",
      options: [
        "Hey, don’t go past the barrier!",
        "Stay behind the barrier, okay?",
        "Visitors are requested to remain behind the barrier.",
        "No going past there, guys."
      ], a: 2,
      why: "Formal writing avoids chatty words (hey, okay, guys) and often uses the passive (“are requested”).",
      hint: "くだけた言葉が無く、受動態を使っているもの" },
    { id: "gr-05", unit: "grammar", skill: "grammar", type: "mc",
      q: "“The cheerful waiter smiled warmly.” What word class is “warmly”?",
      options: ["adjective", "adverb", "verb", "noun"], a: 1,
      why: "“Warmly” tells us HOW he smiled, so it’s an adverb (it describes the verb).",
      hint: "動詞 smiled を説明している＝副詞" },
    { id: "gr-06", unit: "grammar", skill: "grammar", type: "mc",
      q: "“Although it rained, we visited the gardens.” What is “although”?",
      options: ["a preposition", "a determiner", "a subordinating conjunction", "an adverb"], a: 2,
      why: "“Although” starts a clause that can’t stand alone (“although it rained”) and joins it to the main clause.",
      hint: "従属接続詞＝because, when, although, if など" },
    { id: "gr-07", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which sentence shows the LEAST certainty?",
      options: ["It will rain later.", "It is certain to rain later.", "It might rain later.", "It is definitely going to rain later."], a: 2,
      why: "The modal verb “might” shows something is only possible. The other sentences are sure it will happen.",
      hint: "一番「たぶん…かも」なのは？" },
    { id: "gr-08", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which word is an ANTONYM (opposite) of “ancient”?",
      options: ["old", "antique", "modern", "historic"], a: 2,
      why: "Antonyms are opposites. The others all mean something close to “old” (they are synonyms).",
      hint: "antonym＝反対の意味の言葉" },
    { id: "gr-09", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which prefix makes “visible” mean “cannot be seen”?",
      options: ["un-", "dis-", "in-", "mis-"], a: 2,
      why: "in + visible = invisible.",
      hint: "見えない＝???visible" },
    { id: "gr-10", unit: "grammar", skill: "grammar", type: "mc",
      q: "Which sentence is in the present perfect?",
      options: ["I visited Paris twice.", "I have visited Paris twice.", "I am visiting Paris.", "I will visit Paris."], a: 1,
      why: "The present perfect uses have/has + past participle (have visited). It links the past to now.",
      hint: "have / has ＋ 過去分詞" }
  ]
};
